<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="NETOB-Functional" duration-ms="1923" started-at="2016-05-09T13:55:23Z" finished-at="2016-05-09T13:55:25Z">
    <groups>
      <group name="functest">
        <method signature="TestCaseNo1.method1()[pri:0, instance:testcases.TestCaseNo1@76a5994]" name="method1" class="testcases.TestCaseNo1"/>
        <method signature="TestCaseNo1.method3()[pri:0, instance:testcases.TestCaseNo1@76a5994]" name="method3" class="testcases.TestCaseNo1"/>
      </group> <!-- functest -->
      <group name="checkintest">
        <method signature="TestCaseNo1.method1()[pri:0, instance:testcases.TestCaseNo1@76a5994]" name="method1" class="testcases.TestCaseNo1"/>
      </group> <!-- checkintest -->
    </groups>
    <test name="NEt_OB test" duration-ms="1923" started-at="2016-05-09T13:55:23Z" finished-at="2016-05-09T13:55:25Z">
      <class name="testcases.TestCaseNo1">
        <test-method status="PASS" signature="method1()[pri:0, instance:testcases.TestCaseNo1@76a5994]" name="method1" duration-ms="1902" started-at="2016-05-09T16:55:23Z" finished-at="2016-05-09T16:55:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method1 -->
        <test-method status="FAIL" signature="method3()[pri:0, instance:testcases.TestCaseNo1@76a5994]" name="method3" duration-ms="3" started-at="2016-05-09T16:55:25Z" finished-at="2016-05-09T16:55:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<true> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at testcases.TestCaseNo1.method3(TestCaseNo1.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method3 -->
      </class> <!-- testcases.TestCaseNo1 -->
    </test> <!-- NEt_OB test -->
  </suite> <!-- NETOB-Functional -->
</testng-results>
